name: CI docs

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  linux:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 1000
    - name: install docs dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz python3-pip
        pip install breathe sphinx
        pip install -r docs/requirements.txt
    - name: build docs
      shell: bash
      run: |
          EVENT_CMAKE_OPTIONS="-DLIBFS_DOXYGEN=ON"
          mkdir -p build
          cd build
          echo [cmake]: cmake .. $EVENT_CMAKE_OPTIONS
          cmake .. $EVENT_CMAKE_OPTIONS || (rm -rf * && cmake .. $EVENT_CMAKE_OPTIONS)
          cmake --build .
          make
