name: CI docs

on:
  push:
    paths-ignore:
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "LICENSE"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz python3-pip
          pip install breathe sphinx
          pip install -r docs/requirements.txt
      - name: Build docs
        run: |
          EVENT_CMAKE_OPTIONS="-DLIBFS_DOXYGEN=ON"
          mkdir -p build
          cd build
          cmake .. $EVENT_CMAKE_OPTIONS || (rm -rf * && cmake .. $EVENT_CMAKE_OPTIONS)
          cmake --build .
          make
